In [44]:
import pandas as pd

In [45]:
df_ai = pd.read_csv('data/ai_ml_articles_20250723_132012.csv')
df_ai = df_ai.drop(columns=['url'], axis = 0)
df_ai.head()

,title,word_count,content
0,The Open Medical-LLM Leaderboard: Benchmarking...,1359,"Datasets, Tasks, and Evaluation SetupMedQAMedM..."
1,Director of Machine Learning Insights [Part 2:...,2894,Omar Rahman1. How has ML made a positive impac...
2,Hands‑On with Agents SDK: Your First API‑Calli...,2387,"Publish AI, ML & data-science insights to a gl..."
3,4M Models Scanned: Protect AI + Hugging Face 6...,1250,Maintaining a Zero Trust Approach to Model Sec...
4,Judge Arena: Benchmarking LLMs as Evaluators,517,Judge ArenaHow it worksSelected ModelsThe Lead...

In [66]:
df_ar = pd.read_csv('data/arxiv_ai_abstracts.csv')
df_ar['content'] = df_ar['Content']
df_ar['title'] = df_ar['Title']
df_ar = df_ar.drop(columns=['Content', 'Title'], axis = 0)
df_ar['word_count'] = df_ar['content'].apply(lambda x: len(x.split()))
df_ar.head()

,content,title,word_count
0,Vision-language-action (VLA) reasoning tasks r...,ThinkAct: Vision-Language-Action Reasoning via...,145
1,Enhancing large vision-language models (LVLMs)...,Semi-off-Policy Reinforcement Learning for Vis...,225
2,While existing image-guided composition method...,HOComp: Interaction-Aware Human-Object Composi...,215
3,Scientific reasoning is critical for developin...,MegaScience: Pushing the Frontiers of Post-Tra...,226
4,Register Transfer Level(RTL) code optimization...,Rethinking LLM-Based RTL Code Optimization Via...,265

In [47]:
df_blog = pd.read_csv('data/blogspot_ai_ml_scraped_data_100_per_blog.csv')
df_blog = df_blog.drop(columns=['url'], axis=0)
df_blog['word_count'] = df_blog['content'].apply(lambda x: len(x.split()))
df_blog.head()

,title,content,word_count
0,"Planet for AI, OpenAI, Machine Learning, Data ...",Multimodal machine learning is a game-changer ...,545
1,Mastering AI with Python: A Comprehensive Guid...,Python has solidified its\nposition as the lea...,567
2,The Ultimate Guide to Generative AI with Pytho...,Generative AI (GenAI) is one of the most excit...,830
3,"Planet for AI, OpenAI, Machine Learning, Data ...",1. What is Machine Learning? Machine Learning ...,453
4,7-Day Python for AI: A Beginner’s Journey to M...,I’m excited to share that I’ll be launching a ...,1141

In [63]:
df_ds = pd.read_csv('data/datascienceplus_articles.csv')
df_ds['title'] = df_ds['Title']
df_ds['word_count'] = df_ds['Content'].apply(lambda x: len(str(x).split()) if pd.notnull(x) else 0)
df_ds['content'] = df_ds['Content']
df_ds = df_ds.drop(columns=['URL', 'Date', 'Content', 'Title'], axis=0)
df_ds.head()

,title,word_count,content
0,Linking R and Python to retrieve financial dat...,408,I am way more experienced with R than with Pyt...
1,An R alternative to pairs for -omics QC,433,The Problem:I've got a couple of problems with...
2,Visualizing economic data with pretty worldmaps,115,Choropleths are a nice tool for the visualizat...
3,How to Incorporate ML.Net With Algorithmic Tra...,1000,"As you search about ML.Net on Google, you’d fi..."
4,How I selected my starting word for Wordle usi...,861,Wordlehas been around for some time now and I ...

In [ ]:

df_last = pd.read_csv('data/last20250725_122248.csv')
df_last = df_last.drop(columns=['url'], axis = 0)
df_last.head()

,title,word_count,content
0,Untitled,0,NaN
1,Research Debt,1787,Chris Olah Google Brain Shan Carter Google Bra...
2,Untitled,0,NaN
3,"Gemini Deep Think learns math, wins gold medal...",967,"DeepMind followed IMO rules to earn gold, unli..."
4,Untitled,0,NaN

In [ ]:
df_data = pd.read_csv('data/Ltr20250724_123704.csv')
df_data_ = df_data.drop(columns=['url'], axis=0, inplace=True)
df_data.head()

,title,word_count,content
0,"Spacecrafts Can Think for Themselves, Thanks t...",551,Micron Technologyclaims to have launched the i...
1,This “robot bird” flies at 45 mph through fore...,581,"Unlike birds, which navigate unknown environme..."
2,The Future of Fake: Why Artificial Intelligenc...,647,"In 2025, the influence no longer belongs to hu..."
3,Google Expands Firebase Studio with AI Tools f...,533,Google hasannounceda series of updates toFireb...
4,AI Replaced My Job… So I Let It Manage My Sche...,733,I did not think that AI would affect my career...

In [ ]:
df_sh = pd.read_csv('data/shyambhu_all_posts.csv')
df_sh['content'] = df_sh['text']
df_sh = df_sh.drop(columns=['url', 'published_date', 'text'], axis=0)
df_sh['word_count'] = df_sh['content'].apply(lambda x: len(x.split()))
df_sh.head()

,title,content,word_count
0,Understanding LDA and QDA: A Comparative Guide,Certainly! Here's a comprehensive blog post th...,505
1,20 Must-Know Math Puzzles for Data Science Int...,Introduction:\n \nWhen preparing for a data sc...,1391
2,A look in probability for data science,To have a solid foundation in \nprobability th...,1476
3,Interview Dialogue: Customer Churn Prediction ...,Introduction:\nCase studies are a fundamental ...,1529
4,FinancePy: A Comprehensive Python Library for ...,The \nfinancepy\n package is a Python library ...,342

In [ ]:
df_1 = pd.read_csv('data/ian1.csv')
df_1 = df_1.drop(columns=['url'])
df_1.head()

,title,word_count,content
0,Study could lead to LLMs that are better at co...,1022,Suggestions or feedback? Images for download o...
1,How we really judge AI,826,Suggestions or feedback? Previous imageNext im...
2,MIT Learn offers “a whole new front door to th...,1186,Suggestions or feedback? Previous imageNext im...
3,Data quality for unbiased results: Preventing ...,1467,Data Science Central Data Science Central Arti...
4,Ethics-driven model auditing and bias mitigation,1669,Data Science Central Data Science Central Arti...

In [ ]:
df2 = pd.read_csv('data/ian2.csv')
df2 = df2.drop(columns=['url'])
df2.head()

,title,word_count,content
0,Bitcoin Price Analysis as a Tool for Blockchai...,1126,The Data Scientist For blockchain decision-mak...
1,Updates from the NeurIPS 2025 Position Paper T...,727,Communications Chairs 20252025 Conference Barb...
2,Tech giants split on EU AI code as compliance ...,1074,AI News is part of the TechForge Publications ...
3,Import AI,2190,"Welcome to Import AI, a newsletter about AI re..."
4,How to use AI to start an online business,1015,AI News is part of the TechForge Publications ...

In [ ]:
df3 = pd.read_csv('data/ian3.csv')
df3 = df3.drop(columns=['url'])
df3.head()

,title,word_count,content
0,Study could lead to LLMs that are better at co...,1022,Suggestions or feedback? Images for download o...
1,How we really judge AI,826,Suggestions or feedback? Previous imageNext im...
2,MIT Learn offers “a whole new front door to th...,1186,Suggestions or feedback? Previous imageNext im...
3,Data quality for unbiased results: Preventing ...,1467,Data Science Central Data Science Central Arti...
4,Ethics-driven model auditing and bias mitigation,1669,Data Science Central Data Science Central Arti...

In [67]:
df_merge = pd.concat([df_ai, df_ar, df_blog, df_ds, df_last, df_data, df_sh, df_1, df2, df3], ignore_index=True)
df_merge.head()

,title,word_count,content
0,The Open Medical-LLM Leaderboard: Benchmarking...,1359,"Datasets, Tasks, and Evaluation SetupMedQAMedM..."
1,Director of Machine Learning Insights [Part 2:...,2894,Omar Rahman1. How has ML made a positive impac...
2,Hands‑On with Agents SDK: Your First API‑Calli...,2387,"Publish AI, ML & data-science insights to a gl..."
3,4M Models Scanned: Protect AI + Hugging Face 6...,1250,Maintaining a Zero Trust Approach to Model Sec...
4,Judge Arena: Benchmarking LLMs as Evaluators,517,Judge ArenaHow it worksSelected ModelsThe Lead...

In [68]:
df_merge.shape

(4822, 3)

In [70]:
df_merge.duplicated().value_counts()

False    4670
True      152
dtype: int64

In [71]:
df_merge = df_merge.drop_duplicates(subset=['title', 'content'], keep='first')
df_merge.shape

(4670, 3)

In [79]:
df_merge = df_merge[df_merge['word_count'] >= 100]
df_merge.shape

(4452, 3)

In [80]:
df_merge.to_csv('data/merged_data.csv', index=False)
print("Data merging completed and saved to 'data/merged_data.csv'.")

Data merging completed and saved to 'data/merged_data.csv'.