In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
df_1 = pd.read_csv("datasets/1.csv")
df_1.head()

,title,url,word_count,content
0,Untitled,https://aibusiness.com/language-models/how-wim...,0,NaN
1,Research Debt,https://distill.pub/2017/research-debt,1787,Chris Olah Google Brain Shan Carter Google Bra...
2,Untitled,https://aibusiness.com/nvidia/nvidia-dethrones...,0,NaN
3,"Gemini Deep Think learns math, wins gold medal...",https://arstechnica.com/ai/2025/07/google-deep...,967,"DeepMind followed IMO rules to earn gold, unli..."
4,Untitled,https://aibusiness.com/computer-vision/compute...,0,NaN

In [3]:

df_2= pd.read_csv("datasets/2.csv")
df_2.head()

,title,url,word_count,content
0,Thank you for your patience,https://www.microsoft.com/en-us/research/blog/...,14,We are currently experiencing high demand. Ple...
1,Why Doesn’t My Model Work?,https://thegradient.pub/why-doesnt-my-model-work/,3665,Have you ever trained a model you thought was ...
2,Ask a Techspert: What is inference?,https://blog.google/technology/ai/ask-a-techsp...,1376,"Jun 23, 2025 Inference is a big part of what’s..."
3,The Artificiality of Alignment,https://thegradient.pub/the-artificiality-of-a...,3789,"This essay first appeared inReboot. Credulous,..."
4,What's Missing From LLM Chatbots: A Sense of P...,https://thegradient.pub/dialog/,2658,LLM-based chatbots’ capabilities have been adv...

In [4]:
df_3= pd.read_csv("datasets/3.csv")
df_3.head()

,title,url,word_count,content
0,Study could lead to LLMs that are better at co...,https://news.mit.edu/2025/study-could-lead-llm...,1022,Suggestions or feedback? Images for download o...
1,How we really judge AI,https://news.mit.edu/2025/how-we-really-judge-...,826,Suggestions or feedback? Previous imageNext im...
2,MIT Learn offers “a whole new front door to th...,https://news.mit.edu/2025/mit-learn-offers-who...,1186,Suggestions or feedback? Previous imageNext im...
3,Data quality for unbiased results: Preventing ...,https://www.datasciencecentral.com/data-qualit...,1467,Data Science Central Data Science Central Arti...
4,Ethics-driven model auditing and bias mitigation,https://www.datasciencecentral.com/ethics-driv...,1669,Data Science Central Data Science Central Arti...

In [5]:
df_4= pd.read_csv("datasets/4.csv")
df_4.head()

,title,url,word_count,content
0,Bitcoin Price Analysis as a Tool for Blockchai...,https://thedatascientist.com/bitcoin-price-ana...,1126,The Data Scientist For blockchain decision-mak...
1,Updates from the NeurIPS 2025 Position Paper T...,https://blog.neurips.cc/2025/06/06/updates-fro...,727,Communications Chairs 20252025 Conference Barb...
2,Tech giants split on EU AI code as compliance ...,https://www.artificialintelligence-news.com/ne...,1074,AI News is part of the TechForge Publications ...
3,Import AI,https://jack-clark.net/2025/06/23/import-ai-41...,2190,"Welcome to Import AI, a newsletter about AI re..."
4,How to use AI to start an online business,https://www.artificialintelligence-news.com/ne...,1015,AI News is part of the TechForge Publications ...

In [6]:
df_5= pd.read_csv("datasets/5.csv")
df_5.head()

,title,url,word_count,content
0,"Spacecrafts Can Think for Themselves, Thanks t...",https://analyticsindiamag.com/ai-news-updates/...,551,Micron Technologyclaims to have launched the i...
1,This “robot bird” flies at 45 mph through fore...,https://www.sciencedaily.com/releases/2025/06/...,581,"Unlike birds, which navigate unknown environme..."
2,The Future of Fake: Why Artificial Intelligenc...,https://hackernoon.com/the-future-of-fake-why-...,647,"In 2025, the influence no longer belongs to hu..."
3,Google Expands Firebase Studio with AI Tools f...,https://analyticsindiamag.com/ai-news-updates/...,533,Google hasannounceda series of updates toFireb...
4,AI Replaced My Job… So I Let It Manage My Sche...,https://hackernoon.com/ai-replaced-my-job-so-i...,733,I did not think that AI would affect my career...

In [7]:
df_ai_ml = pd.read_csv("datasets/ai_ml_articles.csv")
df_ai_ml.head()

,title,url,word_count,content
0,The Open Medical-LLM Leaderboard: Benchmarking...,https://huggingface.co/blog/leaderboard-medica...,1359,"Datasets, Tasks, and Evaluation SetupMedQAMedM..."
1,Director of Machine Learning Insights [Part 2:...,https://huggingface.co/blog/ml-director-insigh...,2894,Omar Rahman1. How has ML made a positive impac...
2,Hands‑On with Agents SDK: Your First API‑Calli...,https://towardsdatascience.com/hands%e2%80%91o...,2387,"Publish AI, ML & data-science insights to a gl..."
3,4M Models Scanned: Protect AI + Hugging Face 6...,https://huggingface.co/blog/pai-6-month,1250,Maintaining a Zero Trust Approach to Model Sec...
4,Judge Arena: Benchmarking LLMs as Evaluators,https://huggingface.co/blog/arena-atla,517,Judge ArenaHow it worksSelected ModelsThe Lead...

In [8]:
df_arxiv = pd.read_csv("datasets/arxiv_ai_abstracts.csv")
df_arxiv.head()

,Title,Content
0,ThinkAct: Vision-Language-Action Reasoning via...,Vision-language-action (VLA) reasoning tasks r...
1,Semi-off-Policy Reinforcement Learning for Vis...,Enhancing large vision-language models (LVLMs)...
2,HOComp: Interaction-Aware Human-Object Composi...,While existing image-guided composition method...
3,MegaScience: Pushing the Frontiers of Post-Tra...,Scientific reasoning is critical for developin...
4,Rethinking LLM-Based RTL Code Optimization Via...,Register Transfer Level(RTL) code optimization...

In [9]:
df_datascienceplus = pd.read_csv("datasets/datascienceplus_articles.csv")
df_datascienceplus.head()

,Title,URL,Date,Content
0,Linking R and Python to retrieve financial dat...,https://datascienceplus.com/linking-r-and-pyth...,2022-04-17T20:02:48,I am way more experienced with R than with Pyt...
1,An R alternative to pairs for -omics QC,https://datascienceplus.com/an-r-alternative-t...,2022-03-27T20:23:19,The Problem:I've got a couple of problems with...
2,Visualizing economic data with pretty worldmaps,https://datascienceplus.com/visualizing-econom...,2022-03-22T13:56:14,Choropleths are a nice tool for the visualizat...
3,How to Incorporate ML.Net With Algorithmic Tra...,https://datascienceplus.com/how-to-incorporate...,2022-03-17T19:58:25,"As you search about ML.Net on Google, you’d fi..."
4,How I selected my starting word for Wordle usi...,https://datascienceplus.com/how-i-selected-my-...,2022-02-23T20:19:34,Wordlehas been around for some time now and I ...

In [10]:
df_shyambhu=pd.read_csv("datasets/shyambhu_all_posts.csv")
df_shyambhu.head()

,title,url,published_date,text
0,Understanding LDA and QDA: A Comparative Guide,https://shyambhu20.blogspot.com/2025/04/unders...,NaN,Certainly! Here's a comprehensive blog post th...
1,20 Must-Know Math Puzzles for Data Science Int...,https://shyambhu20.blogspot.com/2024/09/20-mus...,NaN,Introduction:\n \nWhen preparing for a data sc...
2,A look in probability for data science,https://shyambhu20.blogspot.com/2024/09/a-look...,NaN,To have a solid foundation in \nprobability th...
3,Interview Dialogue: Customer Churn Prediction ...,https://shyambhu20.blogspot.com/2024/09/Case-s...,NaN,Introduction:\nCase studies are a fundamental ...
4,FinancePy: A Comprehensive Python Library for ...,https://shyambhu20.blogspot.com/2024/09/financ...,NaN,The \nfinancepy\n package is a Python library ...

In [11]:
dfs = [
    df_1, df_2, df_3, df_4, df_5,
    df_ai_ml, df_arxiv, df_datascienceplus, df_shyambhu
]
# Combine all DataFrames into one
df_merged = pd.concat(dfs, ignore_index=True)

In [12]:
df_merged.info()
df_merged.head()

df_merged.to_csv("datasets/merged_articles.csv", index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4001 entries, 0 to 4000
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           1517 non-null   object
 1   url             1517 non-null   object
 2   word_count      1364 non-null   float64
 3   content         1311 non-null   object
 4   Title           2484 non-null   object
 5   Content         2483 non-null   object
 6   URL             484 non-null    object
 7   Date            484 non-null    object
 8   published_date  0 non-null      float64
 9   text            153 non-null    object
dtypes: float64(2), object(8)
memory usage: 312.7+ KB

In [13]:
df_merged.duplicated().sum()  # Check for duplicates

0